fix

diff --git a/.github/workflows/kernel-a12.yml b/.github/workflows/kernel-a12.yml
--- a/.github/workflows/kernel-a12.yml
+++ b/.github/workflows/kernel-a12.yml
@@ -1,35 +1,292 @@
 name: Build Kernel - A12
 
 permissions:
-  contents: write  # Allow writing to repository contents
-  actions: write   # Allows triggering actions
+  contents: write # Allow writing to repository contents (for pushing tags)
+  actions: write # Allows triggering actions
 
 on:
-  push:
-    paths:
-      - .github/workflows/kernel-a12.yml  # Runs when this workflow file is updated\
   workflow_dispatch:
-  workflow_call:  # This allows this workflow to be called from another workflow
     inputs:
+      build_a12_510:
+        description: "Build a12 5.10?"
+        required: true
+        type: boolean
+        default: false
       make_release:
+        description: "Do you want to create a release?"
         required: true
         type: boolean
         default: true
+      kernelsu_variant:
+        description: "Choose KernelSU"
+        required: true
+        type: choice
+        options:
+          - SukiSU
+        default: SukiSU
+      kernelsu_branch:
+        description: "Choose ksu branch"
+        required: true
+        type: choice
+        options:
+          - Stable
+          - Dev
+          - Other
+        default: Dev
+      kernelsu_branch_other:
+        description: "If 'Other' is selected, specify your custom branch"
+        required: false
+        type: string # This input is required if 'Other' is chosen
+        default: "" # Default is empty, but can be filled in if 'Other' is selected
 
 jobs:
-  build-kernels-a12:
-    strategy:
-      fail-fast: true
-      matrix:
-        include:
-        - sub_level: "X"
-          os_patch_level: "lts"
-          revision: "r1"
-    uses: ./.github/workflows/build.yml
+  build-kernel-a12-5-10:
+    if: ${{ inputs.build_a12_510 }}
+    uses: ./.github/workflows/kernel-a12-5.10.yml
     secrets: inherit
     with:
-      android_version: "android12"
-      kernel_version: "5.10"
-      sub_level: ${{ matrix.sub_level }}
-      os_patch_level: ${{ matrix.os_patch_level }}
-      revision: ${{ matrix.revision }}
+      make_release: ${{ inputs.make_release }}
+      kernelsu_variant: ${{ inputs.kernelsu_variant }}
+      kernelsu_branch: ${{ inputs.kernelsu_branch }}
+      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}
+
+  trigger-release:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+      actions: write
+    needs:
+      - build-kernel-a12-5-10
+    if: ${{ inputs.make_release }}
+    env:
+      REPO_OWNER: xxirfanx
+      REPO_NAME: suki_su
+      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
+      # RELEASE_NAME: "GKI Kernels With KernelSU-${{ inputs.kernelsu_variant }} ${{ inputs.kernelsu_branch }} & SUSFS v1.5.7 *TEST BUILD*"
+      RELEASE_NOTES: |
+        > [!CAUTION]
+        > Take your own risk! Nobody tested. `fastboot boot` bofore flash it.
+
+        Features:
+        - ${{ inputs.kernelsu_variant }} (${{ inputs.kernelsu_branch }})
+        - **ඞ** SUSFS
+        - Manual Syscall Hooks
+        - Wireguard Support
+        - BBR Support
+
+        Usage: 
+          - Use [HorizonKernelFlasher](https://github.com/libxzr/HorizonKernelFlasher). Don't use Kernel Flasher, it is broken.
+          - Another way (same as update), is, touch “Working”(status) card in SukiSU Ultra, touch GKI/non-GKI installation, touch Install Anykernel3, then select AnyKernel3 zip file.
+
+        > [!NOTE]  
+        > SUS SU Mode 2 will show as disabled or not compatble due to non-kprobe hooks and is not needed anymore! 
+
+        SUSFS manage WebUI: 
+        - https://github.com/sidex15/susfs4ksu-module
+
+    steps:
+      # Get Date
+      - name: Get current date
+        id: date
+        run: |
+          echo "currentdate=$(date +"%Y-%m-%d-%H-%M-%S")" >> $GITHUB_ENV
+
+      # Checkout the code
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Determine the branch for KernelSU-${{ inputs.kernelsu_variant }}
+        if: ${{ inputs.kernelsu_branch == 'Dev' || inputs.kernelsu_variant == 'SukiSU' }}
+        run: |
+          # Determine the branch based on user input
+          if [[ "${{ inputs.kernelsu_variant }}" == "SukiSU" ]]; then
+            BRANCH="main"
+          elif [[ "${{ inputs.kernelsu_branch }}" == "Other" && -n "${{ inputs.kernelsu_branch_other }}" ]]; then
+            BRANCH="${{ inputs.kernelsu_branch_other }}"
+          else
+            echo "Error: Custom branch not provided for 'Other'" >&2
+            exit 1
+          fi
+
+          # Store the selected branch in GITHUB_ENV
+          echo "KSU_BRANCH=$BRANCH" >> $GITHUB_ENV
+
+      - name: Get commit hash or tag and generate URL for KernelSU-${{ inputs.kernelsu_variant }}
+        run: |
+          if [ "${{ inputs.kernelsu_variant }}" == "SukiSU" ]; then
+            echo "This is the SukiSU variant"
+            REPO_URL="https://github.com/SukiSU-Ultra/SukiSU-Ultra.git"
+            REPO_URL2="SukiSU-Ultra/SukiSU-Ultra"
+          else
+            echo "Unknown variant"
+          fi
+
+          if [[ "${{ inputs.kernelsu_branch }}" == "Stable" && "${{ inputs.kernelsu_variant }}" != "SukiSU" ]]; then
+            # Fetch the latest tag
+            TAG=$(git ls-remote --tags --sort=-v:refname $REPO_URL | grep -o 'refs/tags/.*' | cut -d'/' -f3 | head -n1)
+            if [[ -z "$TAG" ]]; then
+              echo "Error: Could not fetch latest tag for Stable" >&2
+              exit 1
+            fi
+            KSU_REF=$TAG
+            KSU_URL="https://github.com/$REPO_URL2/releases/tag/$TAG"
+
+          elif [[ "${{ inputs.kernelsu_branch }}" == "Dev" || "${{ inputs.kernelsu_variant }}" == "SukiSU" ]]; then
+            # Fetch the latest commit from "next" branch
+            COMMIT_HASH=$(git ls-remote $REPO_URL refs/heads/$KSU_BRANCH | awk '{ print $1 }')
+            if [[ -z "$COMMIT_HASH" ]]; then
+              echo "Error: Could not fetch latest commit for Dev" >&2
+              exit 1
+            fi
+            KSU_REF=$COMMIT_HASH
+            KSU_URL="https://github.com/$REPO_URL2/commit/$COMMIT_HASH"
+
+          else
+            # Fetch the specific tag
+            TAG=${{ inputs.kernelsu_branch_other }}
+            if git ls-remote --tags $REPO_URL | grep -q "refs/tags/$TAG"; then
+              KSU_REF=$TAG
+              KSU_URL="https://github.com/$REPO_URL2/releases/tag/$TAG"
+            else
+              echo "Error: Specified tag '$TAG' not found in KernelSU-Next" >&2
+              exit 1
+            fi
+          fi
+
+          # Echo the values to GitHub environment for later use
+          echo "KSU_REF=$KSU_REF" >> $GITHUB_ENV
+          echo "KSU_URL=$KSU_URL" >> $GITHUB_ENV
+          echo "KernelSU Reference: $KSU_REF"
+          echo "KernelSU URL: $KSU_URL"
+
+      - name: Get commit hashes and generate commit URLs
+        run: |
+          GITLAB_OWNER="simonpunk"
+          GITLAB_REPO="susfs4ksu"
+
+          declare -A BRANCH_MAP=(
+            ["gki_android12_5_10"]="gki-android12-5.10"
+          )
+
+          for var_name in "${!BRANCH_MAP[@]}"; do
+            branch_name="${BRANCH_MAP[$var_name]}"
+            COMMIT_HASH=$(git ls-remote https://gitlab.com/$GITLAB_OWNER/$GITLAB_REPO.git refs/heads/$branch_name | awk '{ print $1 }')
+
+            if [[ -n "$COMMIT_HASH" ]]; then
+              COMMIT_URL="https://gitlab.com/$GITLAB_OWNER/$GITLAB_REPO/-/commit/$COMMIT_HASH"
+              echo "$branch_name Commit: $COMMIT_HASH"
+              echo "$branch_name Commit URL: $COMMIT_URL"
+
+              # Store commit hash and commit URL in GitHub environment
+              echo "COMMIT_HASH_${var_name}=$COMMIT_HASH" >> "$GITHUB_ENV"
+              echo "COMMIT_URL_${var_name}=$COMMIT_URL" >> "$GITHUB_ENV"
+            fi
+          done
+
+      - name: Append Commit Hashes & Links to `RELEASE_NOTES` & Append KernelSU-Next Reference to `RELEASE_NOTES`
+        run: |
+          if [ "${{ inputs.kernelsu_variant }}" == "SukiSU" ]; then
+            echo "This is the SukiSU variant"
+            echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
+            echo "$RELEASE_NOTES" >> $GITHUB_ENV
+            echo "SukiSU Ultra Manager:" >> $GITHUB_ENV
+            echo "- https://github.com/SukiSU-Ultra/SukiSU-Ultra" >> $GITHUB_ENV
+            echo "EOF" >> $GITHUB_ENV
+          else
+            echo "Unknown variant"
+          fi
+
+      - name: Append Commit Hashes & Links to `RELEASE_NOTES` & Append KernelSU-Next Reference to `RELEASE_NOTES`
+        run: |
+          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
+          echo "$RELEASE_NOTES" >> $GITHUB_ENV
+          echo "" >> $GITHUB_ENV
+          echo "LTO: thin" >> $GITHUB_ENV
+          echo "<details>" >> $GITHUB_ENV
+          echo "<summary>Commit Hashes and Links</summary>" >> $GITHUB_ENV
+          echo "" >> $GITHUB_ENV
+          echo "- KernelSU:" >> $GITHUB_ENV
+          echo "  - ${{ inputs.kernelsu_variant }}-${{ inputs.kernelsu_branch }}: [$KSU_REF]($KSU_URL)" >> $GITHUB_ENV
+          echo "- SUSFS4KSU:" >> $GITHUB_ENV
+          echo "  - gki-android12-5.10: [$COMMIT_HASH_gki_android12_5_10]($COMMIT_URL_gki_android12_5_10)" >> $GITHUB_ENV
+          echo "" >> $GITHUB_ENV
+          echo "</details>" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+
+      # Get the Latest Tag from GitHub
+      - name: Generate and Create New Tag
+        env:
+          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
+        run: |
+          # Fetch the latest tag from GitHub (this is the latest tag based on the GitHub API)
+          LATEST_TAG=$(gh api repos/$REPO_OWNER/$REPO_NAME/tags --jq '.[0].name')
+          if [ -z "$LATEST_TAG" ]; then
+            LATEST_TAG="v1.5.5-r0"
+          fi
+
+          # NEW_TAG=$(echo "$LATEST_TAG" | awk -F'-r' '{suffix=$2; if (!suffix) suffix=0; suffix++; printf "%s-r%d", $1, suffix}')
+          NEW_TAG=${{ env.currentdate }}
+
+          # Output the new tag to be used
+          echo "New tag: $NEW_TAG"
+
+          # Set the new tag as an environment variable to be used in later steps
+          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV
+
+          # Create the tag in the repository
+          git tag $NEW_TAG
+          git push --tags
+
+      # Download Artifacts for A12 (Only if A12 Build is successful or input is true or empty)
+      - name: Download Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          path: ./downloaded-artifacts
+
+      # Create GitHub Release and upload files if make_release is true
+      - name: Create GitHub Release
+        uses: actions/create-release@v1
+        with:
+          tag_name: ${{ env.currentdate }} # Use the generated tag for the release
+          prerelease: true # Mark the release as a pre-release
+          release_name: ${{ env.currentdate }} # Pass the RELEASE_NAME to the action
+          body: ${{ env.RELEASE_NOTES }} # Pass the RELEASE_NOTES to the action
+
+      - name: Upload Release Assets Dynamically
+        run: |
+          # Loop through all files in the downloaded-artifacts directory
+          for file in ./downloaded-artifacts/kernel-*/*; do
+              # Skip directories
+              if [ -d "$file" ]; then
+                  continue
+              fi
+
+              # Upload the file to the GitHub release
+              echo "Uploading $file..."
+              gh release upload ${{ env.NEW_TAG }} "$file"
+          done
+
+      # Display Files Uploaded
+      - name: Display Files Uploaded
+        run: |
+          echo "GitHub release created with the following files:"
+          ls ./downloaded-artifacts/**/*
+
+      - name: Send telegram message on push
+        env:
+          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
+          TELEGRAM_MESSAGE_THREAD_ID: ${{ secrets.TELEGRAM_MESSAGE_THREAD_ID }}
+        # run: |
+        #   curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
+        #     -d "chat_id=$TELEGRAM_CHAT_ID" \
+        #     -d "message_thread_id=$TELEGRAM_MESSAGE_THREAD_ID" \
+        #     -d "text=Latest release:
+        #     https://github.com/ShirkNeko/GKI_KernelSU_SUSFS/releases/tag/${{ env.NEW_TAG }}"
+        run: |
+          curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
+            -d "chat_id=-100$TELEGRAM_CHAT_ID" \
+            -d "text=新推送 ${{ env.currentdate }}
+          https://github.com/xxirfanx/suki_su/releases/tag/${{ env.NEW_TAG }}
+          请在有另一台设备的情况下安装。此构建暂未经过测试。
+            "
